name: Build and Deploy

on: 
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: borales/actions-yarn@v2.0.1
      with:
          cmd: install
    - uses: borales/actions-yarn@v2.0.1
      with:
        cmd: build
      env:
        CI: true
    - name: Run Hue Action
      uses: manekinekko/hue-action@v1.0
      if: success()
      with:
        hueWebhook: ${{ secrets.HUEACTION_WEBHOOK }}
        hueLightId: "5"
        hueStatus: "success"
    - name: Run Hue Action
      uses: manekinekko/hue-action@v1.0
      if: failure()
      with:
        hueWebhook: ${{ secrets.HUEACTION_WEBHOOK }}
        hueLightId: "5"
        hueStatus: "failure"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: borales/actions-yarn@v2.0.1
      with:
        cmd: install
    - uses: borales/actions-yarn@v2.0.1
      with:
        cmd: build
    - name: Clean install dependencies and build
      run: |
        yarn deploy
      env:
        CI: true
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
